"""
Sample Output: AI-Generated Pytest Test Cases for POST /users endpoint
Generated by: AI-Powered API Test Generator
Model Used: Groq LLaMA 3.3 70B
"""

import requests

BASE_URL = "http://localhost:8000"

# ============================================================
# A. POSITIVE TESTS - Valid payload, expect 201 Created
# ============================================================

def test_create_user_valid():
    """Happy path: Create a user with valid name and email."""
    payload = {
        "name": "John Doe",
        "email": "john@example.com"
    }
    response = requests.post(f"{BASE_URL}/users", json=payload)
    assert response.status_code == 201

def test_create_user_valid_long_name():
    """Happy path: Create a user with a longer name."""
    payload = {
        "name": "Alexander Benjamin Thompson",
        "email": "alexander@example.com"
    }
    response = requests.post(f"{BASE_URL}/users", json=payload)
    assert response.status_code == 201

# ============================================================
# B. NEGATIVE TESTS - Missing fields or invalid data, expect 400
# ============================================================

def test_create_user_missing_name():
    """Negative: Missing required 'name' field should return 400."""
    payload = {
        "email": "john@example.com"
    }
    response = requests.post(f"{BASE_URL}/users", json=payload)
    assert response.status_code == 400

def test_create_user_missing_email():
    """Negative: Missing required 'email' field should return 400."""
    payload = {
        "name": "John Doe"
    }
    response = requests.post(f"{BASE_URL}/users", json=payload)
    assert response.status_code == 400

def test_create_user_missing_all_fields():
    """Negative: Empty payload should return 400."""
    payload = {}
    response = requests.post(f"{BASE_URL}/users", json=payload)
    assert response.status_code == 400

def test_create_user_invalid_email_format():
    """Negative: Invalid email format should return 400."""
    payload = {
        "name": "John Doe",
        "email": "not-a-valid-email"
    }
    response = requests.post(f"{BASE_URL}/users", json=payload)
    assert response.status_code == 400

def test_create_user_name_as_integer():
    """Negative: Name as integer instead of string should return 400."""
    payload = {
        "name": 12345,
        "email": "john@example.com"
    }
    response = requests.post(f"{BASE_URL}/users", json=payload)
    assert response.status_code == 400

# ============================================================
# C. BOUNDARY TESTS - Edge case values
# ============================================================

def test_create_user_empty_name():
    """Boundary: Empty string for name should return 400."""
    payload = {
        "name": "",
        "email": "john@example.com"
    }
    response = requests.post(f"{BASE_URL}/users", json=payload)
    assert response.status_code == 400

def test_create_user_null_name():
    """Boundary: Null name value should return 400."""
    payload = {
        "name": None,
        "email": "john@example.com"
    }
    response = requests.post(f"{BASE_URL}/users", json=payload)
    assert response.status_code == 400

def test_create_user_null_email():
    """Boundary: Null email value should return 400."""
    payload = {
        "name": "John Doe",
        "email": None
    }
    response = requests.post(f"{BASE_URL}/users", json=payload)
    assert response.status_code == 400

def test_create_user_max_length_name():
    """Boundary: Very long name string."""
    payload = {
        "name": "A" * 500,
        "email": "john@example.com"
    }
    response = requests.post(f"{BASE_URL}/users", json=payload)
    # Either accepted (201) or rejected (400), but must not crash (500)
    assert response.status_code in [201, 400]
