"""
Sample Output: AI-Generated Pytest Test Cases for POST /orders endpoint
Generated by: AI-Powered API Test Generator
Model Used: Groq LLaMA 3.3 70B
"""

import requests

BASE_URL = "http://localhost:8000"

# ============================================================
# A. POSITIVE TESTS - Valid payload, expect 201 Created
# ============================================================

def test_create_order_valid():
    """Happy path: Create an order with valid user_id, item_name, and quantity."""
    payload = {
        "user_id": 1,
        "item_name": "Laptop",
        "quantity": 2
    }
    response = requests.post(f"{BASE_URL}/orders", json=payload)
    assert response.status_code == 201

def test_create_order_minimum_quantity():
    """Happy path: Create an order with minimum valid quantity (1)."""
    payload = {
        "user_id": 5,
        "item_name": "Mouse",
        "quantity": 1
    }
    response = requests.post(f"{BASE_URL}/orders", json=payload)
    assert response.status_code == 201

# ============================================================
# B. NEGATIVE TESTS - Missing fields or invalid data, expect 400
# ============================================================

def test_create_order_missing_user_id():
    """Negative: Missing required 'user_id' field should return 400."""
    payload = {
        "item_name": "Laptop",
        "quantity": 2
    }
    response = requests.post(f"{BASE_URL}/orders", json=payload)
    assert response.status_code == 400

def test_create_order_missing_item_name():
    """Negative: Missing required 'item_name' field should return 400."""
    payload = {
        "user_id": 1,
        "quantity": 2
    }
    response = requests.post(f"{BASE_URL}/orders", json=payload)
    assert response.status_code == 400

def test_create_order_missing_quantity():
    """Negative: Missing required 'quantity' field should return 400."""
    payload = {
        "user_id": 1,
        "item_name": "Laptop"
    }
    response = requests.post(f"{BASE_URL}/orders", json=payload)
    assert response.status_code == 400

def test_create_order_invalid_quantity_type():
    """Negative: Quantity as string instead of integer should return 400."""
    payload = {
        "user_id": 1,
        "item_name": "Laptop",
        "quantity": "two"
    }
    response = requests.post(f"{BASE_URL}/orders", json=payload)
    assert response.status_code == 400

def test_create_order_invalid_user_id_type():
    """Negative: user_id as string instead of integer should return 400."""
    payload = {
        "user_id": "abc",
        "item_name": "Laptop",
        "quantity": 2
    }
    response = requests.post(f"{BASE_URL}/orders", json=payload)
    assert response.status_code == 400

# ============================================================
# C. BOUNDARY TESTS - Edge case values
# ============================================================

def test_create_order_zero_quantity():
    """Boundary: Zero quantity is below minimum (1), should return 400."""
    payload = {
        "user_id": 1,
        "item_name": "Laptop",
        "quantity": 0
    }
    response = requests.post(f"{BASE_URL}/orders", json=payload)
    assert response.status_code == 400

def test_create_order_negative_quantity():
    """Boundary: Negative quantity should return 400."""
    payload = {
        "user_id": 1,
        "item_name": "Laptop",
        "quantity": -5
    }
    response = requests.post(f"{BASE_URL}/orders", json=payload)
    assert response.status_code == 400

def test_create_order_empty_item_name():
    """Boundary: Empty string for item_name should return 400."""
    payload = {
        "user_id": 1,
        "item_name": "",
        "quantity": 1
    }
    response = requests.post(f"{BASE_URL}/orders", json=payload)
    assert response.status_code == 400

def test_create_order_null_fields():
    """Boundary: Null values for all fields should return 400."""
    payload = {
        "user_id": None,
        "item_name": None,
        "quantity": None
    }
    response = requests.post(f"{BASE_URL}/orders", json=payload)
    assert response.status_code == 400
